# Generated by Django 3.2.5 on 2021-09-22 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('mathematics', 'Mathematics'), ('geometry', 'Geometry'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('literature', 'Literature'), ('hiatory', 'Hiatory')], max_length=50)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/')),
                ('attendants', models.ManyToManyField(blank=True, default=None, related_name='attendants', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
