# Generated by Django 3.2.5 on 2021-09-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_open',
            field=models.BooleanField(choices=[(True, 'Open'), (False, 'closed')], default=False),
        ),
    ]
