# Generated by Django 3.2.5 on 2021-09-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20210923_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_open',
            field=models.BooleanField(choices=[(True, 'Open'), (False, 'close')], default=False),
        ),
    ]
