# Generated by Django 3.2.5 on 2021-09-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_attendant_attendant_attendant_user'),
        ('meeting', '0004_auto_20210924_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='operator', to='user.operator'),
        ),
    ]
