# Generated by Django 3.2.5 on 2021-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_alter_meeting_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
