# Generated by Django 3.2.5 on 2021-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_alter_meeting_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='path',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
