# Generated by Django 3.2.5 on 2021-09-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_alter_meeting_attendants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='is_open',
            field=models.BooleanField(choices=[(True, 'On'), (False, 'Off')], default=False, verbose_name='Status'),
        ),
    ]
