# Generated by Django 3.2.5 on 2021-09-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_alter_meeting_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
