# Generated by Django 3.2.5 on 2021-09-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210923_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendant',
            old_name='attendant',
            new_name='attendant_user',
        ),
    ]
